/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentRecordSystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class StudentRecordSystem extends javax.swing.JFrame 
{
   Connection conn;
   ResultSet rs = null;
   PreparedStatement pst = null;

    /**
     * Creates new form StudentRecordSystem
     */
    public StudentRecordSystem() 
    {
        initComponents();
        conn = DBConnect.ConnercrDB();
        UpdateJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regNumTF = new javax.swing.JTextField();
        lNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deptTF = new javax.swing.JTextField();
        genderCB = new javax.swing.JComboBox<>();
        stateCB = new javax.swing.JComboBox<>();
        searchTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        recordTB = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        exitBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        updateBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        insertBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Record System");

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("STUDENT RECORD SYSTEM");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registration Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("First Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Department");

        lNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("State");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Last Name");

        deptTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptTFActionPerformed(evt);
            }
        });

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GENDER", "Male", "Female" }));
        genderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCBActionPerformed(evt);
            }
        });

        stateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT STATE", "Abia", "Adamawa", "Akwa ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Eboyin", "Edo", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara", "Federal Capital Teritory" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(101, 101, 101))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(fNameTF)
                    .addComponent(genderCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deptTF, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(regNumTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stateCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deptTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        recordTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recordTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Reg no.", "Full Name", "Last Name", "Gender", "State", "Department"
            }
        ));
        recordTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordTBMouseClicked(evt);
            }
        });
        recordTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                recordTBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recordTBKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(recordTB);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        exitBT.setBackground(new java.awt.Color(255, 0, 51));
        exitBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBT.setText("Exit");
        exitBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        resetBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetBT.setText("Reset");
        resetBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTActionPerformed(evt);
            }
        });

        updateBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBT.setText("Update");
        updateBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTActionPerformed(evt);
            }
        });

        deleteBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBT.setText("Delete");
        deleteBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });
        deleteBT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteBTKeyPressed(evt);
            }
        });

        insertBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertBT.setText("INSERT");
        insertBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertBT, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(deleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertBT)
                .addGap(18, 18, 18)
                .addComponent(updateBT)
                .addGap(18, 18, 18)
                .addComponent(deleteBT)
                .addGap(18, 18, 18)
                .addComponent(resetBT)
                .addGap(18, 18, 18)
                .addComponent(exitBT)
                .addGap(40, 40, 40))
        );

        searchBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchBT.setText("Search");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(searchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(searchBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(821, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void  UpdateJTable()
     {
        String sql = " select * from studentTable";
         try
         {
             pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             // line of codesconnecting the jTable to the database
             recordTB.setModel(DbUtils.resultSetToTableModel(rs));
             
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
             
         }
         finally{
             try
             {
                 rs.close();
                 pst.close();
             } catch (Exception e)
             {
             }
         }
         
     }
    private void lNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTFActionPerformed

    private void deptTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptTFActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        try
        {
            String Value1 = regNumTF.getText();
            String value2 = fNameTF.getText();
            String value3 = lNameTF.getText();
            String value4 = genderCB.getSelectedItem().toString(); 
            String value5 = stateCB.getSelectedItem().toString();
            String value6 = deptTF.getText();
            String sql = "update StudentTable set First_Name='" + value2 + "', Last_Name='" + value3 + "',Gender='" + value4 + "',State='" + value5 + "', Department='" + value6 + "' where Registration_Number='" + Value1 + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            UpdateJTable();
            JOptionPane.showMessageDialog(null, "Update");
            
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try
            {
               rs.close();
               pst.close();
               // conn.close();
            } catch (Exception e)
            {
            }
        }
    }//GEN-LAST:event_updateBTActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchTFActionPerformed
    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
       int PromptYesNo = JOptionPane.showConfirmDialog(null,"do you really want to delete","delete record?",JOptionPane.YES_NO_OPTION );
       if (PromptYesNo==0)
       {
           try
           {
               String sql = "delete from studentTable where Registration_Number=?";
               pst = conn.prepareStatement(sql);
               pst.setString(1,regNumTF.getText());
               pst.execute();
               UpdateJTable();
               JOptionPane.showMessageDialog(null,"Delete");
               
           } catch (Exception e)
           {
               JOptionPane.showMessageDialog(null,e);
               
           }
       }   
    }//GEN-LAST:event_deleteBTActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql = "select * from StudentTable where Registration_Number=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,searchTF.getText());
            
            rs = pst.executeQuery();
            //pst.execute();
            if (rs.next()){
                String add1 = rs.getString("Registration_Number");
                regNumTF.setText(add1);
                String add2 = rs.getString("First_Name");
                fNameTF.setText(add2);
                String add3 = rs.getString("Last_Name");
                lNameTF.setText(add3);
                String add4 = rs.getString("Gender");
                genderCB.setSelectedItem(add4);
                
                String add5 = rs.getString("State");
                stateCB.setSelectedItem(add5);
                String add6 = rs.getString("Department");
                deptTF.setText(add6);
                UpdateJTable();
            }
                
        } catch (Exception e)
        {
        }
         finally{
            try
            {
                rs.close();
                pst.close();
                //conn
            } catch (Exception e)
            {
            }
        } 
        //==============================================SEARCH BY First_Name=================================================================================================================================================================================================================================================
        try
        {
            String sql = "select * from StudentTable where First_Name=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,searchTF.getText());
            
            rs = pst.executeQuery();
            //pst.execute();
            if (rs.next()){
                String add1 = rs.getString("Registration_Number");
                regNumTF.setText(add1);
                String add2 = rs.getString("First_Name");
                fNameTF.setText(add2);
                String add3 = rs.getString("Last_Name");
                lNameTF.setText(add3);
                String add4 = rs.getString("Gender");
                genderCB.setSelectedItem(add4);
                
                String add5 = rs.getString("State");
                stateCB.setSelectedItem(add5);
                String add6 = rs.getString("Department");
                deptTF.setText(add6);
                UpdateJTable();
            }
                
        } catch (Exception e)
        {
        }
         finally{
            try
            {
                rs.close();
                pst.close();
                //conn
            } catch (Exception e)
            {
            }
        }
    }//GEN-LAST:event_searchBTActionPerformed
    private void recordTBMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_recordTBMouseClicked
    {//GEN-HEADEREND:event_recordTBMouseClicked
        // TODO add your handling code here:
        int row = recordTB.getSelectedRow();
        regNumTF.setText(recordTB.getModel().getValueAt(row,0).toString());
        fNameTF.setText(recordTB.getModel().getValueAt(row,1).toString());
        lNameTF.setText(recordTB.getModel().getValueAt(row,2).toString());
        genderCB.setSelectedItem(recordTB.getModel().getValueAt(row,3).toString());
        stateCB.setSelectedItem(recordTB.getModel().getValueAt(row,4).toString());
        deptTF.setText(recordTB.getModel().getValueAt(row,5).toString());
        
    }//GEN-LAST:event_recordTBMouseClicked

    private void genderCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_genderCBActionPerformed
    {//GEN-HEADEREND:event_genderCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCBActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitBTActionPerformed
    {//GEN-HEADEREND:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetBTActionPerformed
    {//GEN-HEADEREND:event_resetBTActionPerformed
        // TODO add your handling code here:
        regNumTF.setText(null);
        deptTF.setText(null);
        fNameTF.setText(null);
        lNameTF.setText(null);
        genderCB.setSelectedItem("SELECT GENDER");
        stateCB.setSelectedItem("SELECT STATE");
        searchTF.setText(null);
        
    }//GEN-LAST:event_resetBTActionPerformed

    private void recordTBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_recordTBKeyPressed
    {//GEN-HEADEREND:event_recordTBKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_recordTBKeyPressed

    private void recordTBKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_recordTBKeyReleased
    {//GEN-HEADEREND:event_recordTBKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_recordTBKeyReleased

    private void insertBTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertBTActionPerformed
    {//GEN-HEADEREND:event_insertBTActionPerformed
        // TODO add your handling code here:
          // A CODE TO INSERT RECORD TO THE DATABASE
        String sql = "INSERT INTO studentTable (Registration_Number,First_Name,Last_Name,Gender,State,Department)values(?,?,?,?,?,?)";
        
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1,regNumTF.getText());
            pst.setString(2,fNameTF.getText());
            pst.setString(3,lNameTF.getText());
            pst.setString(4,genderCB.getSelectedItem().toString());
            pst.setString(5,stateCB.getSelectedItem().toString());
            pst.setString(6,deptTF.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "INSERTED");
            UpdateJTable();
            
        }
        catch (Exception e)
        {e.printStackTrace();
        }
    }//GEN-LAST:event_insertBTActionPerformed

    private void deleteBTKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_deleteBTKeyPressed
    {//GEN-HEADEREND:event_deleteBTKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBTKeyPressed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
        this.setTitle("Student Record System"); //Sets the title of this
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //exit out of application
        this.setResizable(false); //prevent this from being resized
        this.setVisible(true); //make this visible
        
        ImageIcon image = new ImageIcon("C:\\Users\\Micoboh\\Documents\\NetBeansProjects\\StudentRecord\\src\\StudentRecordSystem\\a_logo.png"); //Creates an image icon
        this.setIconImage(image.getImage()); //Change Icon of the this
        this.getContentPane().setBackground(new Color(0x123456)); //Chang backgroundColor
    }//GEN-LAST:event_jPanel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecordSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBT;
    private javax.swing.JTextField deptTF;
    private javax.swing.JButton exitBT;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JButton insertBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JTable recordTB;
    private javax.swing.JTextField regNumTF;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField searchTF;
    private javax.swing.JComboBox<String> stateCB;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables
}
